version: "2.1"
services:
  spotweb:
    image: rwscheers/spotweb
    container_name: spotweb
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 80:80
    restart: unless-stopped
networks:
  default:
    external:
      name: docker
